Repository A-Team-Rowan-University/a-team-website, pull requests merged in 2019-09, with the labels that each got.

#81 Migrate to main travis matrix
  .travis.yml
  backend/webdev_lib/.travis.yml
  frontend/elm-src/.travis.yml
Labels: bug

#79 # Add labels to test registrations
  frontend/elm-src/src/TestSessions/TestSession.elm
Labels: enhancement

#83 Allow unregistering
  backend/webdev_lib/src/tests/test_sessions/models.rs
  backend/webdev_lib/src/tests/test_sessions/requests.rs
  frontend/elm-src/src/TestSessions/List.elm
  frontend/elm-src/src/TestSessions/TestSession.elm
Labels: enhancement, priority-high, tests

#87 Update rust to 1.37
  backend/Dockerfile
Labels: enhancement

#94 Change resource-website to a-team-website container
  debug_run.sh
Labels: enhancement, priority-low

#97 #90 docker logs are too long and not super useful
  backend/Cargo.lock
  backend/Cargo.toml
  backend/src/main.rs
  backend/webdev_lib/src/tests/test_sessions/requests.rs
Labels: bug, priority-high

#133 Check for permissions when unregistering someone else
  backend/webdev_lib/src/tests/test_sessions/requests.rs
  frontend/elm-src/src/TestSessions/List.elm
Labels: priority-critical
